INSERT IGNORE INTO `GroupRole` (`id`, `groupType`, `roleName`, `typicalCount`, `ratioToMembers`, `requiredSkills`, `avgLoad`, `occurrences`, `source`, `createdAt`) VALUES
(UUID(), 'constructora pequeña', 'jefe de obra', 1, 0.125, '["gestión de obra","liderazgo","seguridad"]', 8, 1, 'seed', NOW()),
(UUID(), 'constructora pequeña', 'maestro de obra', 2, 0.25, '["albañilería","lectura de planos","supervisión"]', 7, 1, 'seed', NOW()),
(UUID(), 'constructora pequeña', 'oficial albañil', 3, 0.375, '["albañilería","mezclas","herramientas"]', 6, 1, 'seed', NOW()),
(UUID(), 'constructora pequeña', 'administrador', 1, 0.125, '["contabilidad","compras","nómina"]', 5, 1, 'seed', NOW()),
(UUID(), 'constructora pequeña', 'prevencionista', 1, 0.125, '["seguridad laboral","normativa","inspección"]', 4, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'gerente de proyecto', 1, 0.05, '["gestión de proyecto","PMBOK","presupuestos"]', 9, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'jefe de obra', 2, 0.1, '["gestión de obra","liderazgo","seguridad"]', 8, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'maestro de obra', 3, 0.15, '["albañilería","lectura de planos","supervisión"]', 7, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'oficial albañil', 6, 0.3, '["albañilería","mezclas","herramientas"]', 6, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'administrador', 2, 0.1, '["contabilidad","compras","nómina"]', 5, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'prevencionista', 1, 0.05, '["seguridad laboral","normativa","inspección"]', 4, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'topógrafo', 1, 0.05, '["topografía","estación total","GPS"]', 5, 1, 'seed', NOW()),
(UUID(), 'constructora mediana', 'arquitecto', 2, 0.1, '["diseño","Revit","normativa urbana"]', 7, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'director creativo', 1, 0.1, '["dirección de arte","estrategia","pitch"]', 9, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'diseñador senior', 2, 0.2, '["UI/UX","Figma","design systems"]', 8, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'desarrollador full-stack', 2, 0.2, '["React","Node.js","PostgreSQL"]', 8, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'project manager', 1, 0.1, '["Scrum","Jira","gestión de clientes"]', 7, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'copywriter', 1, 0.1, '["copywriting","SEO","branding"]', 5, 1, 'seed', NOW()),
(UUID(), 'agencia digital', 'community manager', 1, 0.1, '["redes sociales","contenido","analítica"]', 4, 1, 'seed', NOW()),
(UUID(), 'restaurante', 'chef ejecutivo', 1, 0.125, '["cocina","menú","proveedores"]', 9, 1, 'seed', NOW()),
(UUID(), 'restaurante', 'sous chef', 1, 0.125, '["cocina","supervisión","inventario"]', 8, 1, 'seed', NOW()),
(UUID(), 'restaurante', 'cocinero', 2, 0.25, '["cocina","preparación","higiene"]', 7, 1, 'seed', NOW()),
(UUID(), 'restaurante', 'mesero', 3, 0.375, '["servicio","atención al cliente","POS"]', 6, 1, 'seed', NOW()),
(UUID(), 'restaurante', 'administrador', 1, 0.125, '["contabilidad","proveedores","personal"]', 5, 1, 'seed', NOW()),
(UUID(), 'taller mecánico', 'jefe de taller', 1, 0.2, '["mecánica","gestión","diagnóstico"]', 8, 1, 'seed', NOW()),
(UUID(), 'taller mecánico', 'mecánico senior', 1, 0.2, '["mecánica general","electrónica","diagnóstico"]', 7, 1, 'seed', NOW()),
(UUID(), 'taller mecánico', 'mecánico', 2, 0.4, '["mecánica","cambio de piezas","mantenimiento"]', 6, 1, 'seed', NOW()),
(UUID(), 'taller mecánico', 'administrador', 1, 0.2, '["facturación","inventario","atención al cliente"]', 4, 1, 'seed', NOW()),
(UUID(), 'consultora', 'socio director', 1, 0.1, '["estrategia","desarrollo de negocio","liderazgo"]', 9, 1, 'seed', NOW()),
(UUID(), 'consultora', 'consultor senior', 2, 0.2, '["análisis","presentaciones","gestión de proyectos"]', 8, 1, 'seed', NOW()),
(UUID(), 'consultora', 'consultor junior', 3, 0.3, '["investigación","Excel","PowerPoint"]', 6, 1, 'seed', NOW()),
(UUID(), 'consultora', 'analista de datos', 1, 0.1, '["SQL","Python","visualización"]', 7, 1, 'seed', NOW()),
(UUID(), 'consultora', 'administrador', 1, 0.1, '["facturación","RRHH","operaciones"]', 4, 1, 'seed', NOW());
