-- AlterTable: AgentRole enum (SYSTEM/EXTERNAL) + createdAt/updatedAt
ALTER TABLE `AgentMembership`
  MODIFY `role` ENUM('ADMIN','MEMBER','SYSTEM','EXTERNAL') NOT NULL DEFAULT 'MEMBER';

UPDATE `AgentMembership` SET `role` = 'EXTERNAL';

ALTER TABLE `AgentMembership`
  CHANGE `joinedAt` `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  MODIFY `role` ENUM('SYSTEM','EXTERNAL') NOT NULL DEFAULT 'EXTERNAL';
