ALTER TABLE `Need` ADD COLUMN `relevanceThresholdMet` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `Need` ADD COLUMN `quorumMet` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `Need` ADD COLUMN `totalPeopleEquivalent` INTEGER NOT NULL DEFAULT 0;
